config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings

  get 'pages/about'

  get 'pages/contact'

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
	else
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg",
					  :storage => :dropbox,
    				  :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    				  :path => ":style/:id_:filename"
    end
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

def devise_error_messages!

return '' if resource.errors.empty?

messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

html = <<-HTML

<div>

<button type="button" data-dismiss="alert" aria-hidden="true">&times;</button>

<h4>#{sentence}</h4>

#{messages}

</div>

HTML

html.html_safe

end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2015</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("logo.png", :alt => "LawyerJury", :title => "Home"), "/") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
       
      </ul> 
       <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %> 
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
         <li><%= link_to "Sign Up", new_user_registration_path %></li>
         <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
       </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
			<% flash.each do |name, msg| %>
			<% if msg.is_a?(String) %>
			<div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>         
<%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>   

	<%= yield %>

	<%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
<div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="center">
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= image_tag listing.image.url %>
        <div class="caption">
          <h3><%= listing.name %></h3>
          <p><%= number_to_currency(listing.price) %></p>
          <%= link_to 'Show', listing, class: "btn btn-link" %>
          <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>
          <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
      </div>
    </div>
    </div>
  <% end %>
</div>
</div>

<br>

<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
		<%= image_tag @listing.image.url %>
	</div>
	</div>
	<div class="col-md-6">
		<h3><%= @listing.name %><h3>
			<p><%= number_to_currency(@listing.price) %></p>
			<p><%= @listing.description %></p>
	</div>
</div>

<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/pages/about.html.erb
<h1>Welcome to TreasureBox.Gallery</h1>
<p>Treasure Box Gallery is an online marketplace for buying and selling your treasured collectibles.</p>

app/views/pages/contact.html.erb
<h1>Contact Form coming soon.</h1>